### ISSUE TITLE
Problem with lmfit?

### ISSUE THREAD

**Issue by ismael-mendoza** [DarkEnergyScienceCollaboration/WeakLensingDeblending#23]
I recently tried running the basic command: 

```
./simulate.py --catalog-name OneDegSq.fits --image-width 300 --image-height 300 --output-name tutorial
```

In my fork and I got the following error: 

```
Traceback (most recent call last):
  File "./simulate.py", line 86, in <module>
    main()
  File "./simulate.py", line 78, in main
    results = analyzer.finalize(args.verbose,trace,args.calculate_bias)
  File "/Users/Ismael/WeakLensingDeblending/descwl/analysis.py", line 1003, in finalize
    bestfit = self.fit_galaxies([g1],deblended)
  File "/Users/Ismael/WeakLensingDeblending/descwl/analysis.py", line 661, in fit_galaxies
    minimum = lmfit.minimize(residuals,parameters)
  File "/Users/Ismael/miniconda2/lib/python2.7/site-packages/lmfit/minimizer.py", line 1543, in minimize
    return fitter.minimize(method=method)
  File "/Users/Ismael/miniconda2/lib/python2.7/site-packages/lmfit/minimizer.py", line 1242, in minimize
    return function(**kwargs)
  File "/Users/Ismael/miniconda2/lib/python2.7/site-packages/lmfit/minimizer.py", line 1072, in leastsq
    lsout = scipy_leastsq(self.__residual, vars, **lskws)
  File "/Users/Ismael/miniconda2/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 377, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
  File "/Users/Ismael/miniconda2/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 26, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/Users/Ismael/miniconda2/lib/python2.7/site-packages/lmfit/minimizer.py", line 371, in __residual
    out = _nan_policy(out, nan_policy=self.nan_policy)
  File "/Users/Ismael/miniconda2/lib/python2.7/site-packages/lmfit/minimizer.py", line 1432, in _nan_policy
    raise ValueError("The input contains nan values")
ValueError: The input contains nan values
```
I tried to `git clone` the repository  just to make sure it was not my fork. This still produced the error above running the same command. 
I also updated my version of `lmfit` without any success. Not sure what could be the problem.

**Comment by fjaviersanchez** [comment]
So it looks like the default nan policy in lmfit is now 'raise' and before was 'omit'. I created a `Minimizer` object to solve this before calling the minimize step. This will be solved when I merge the branch `adding_stars` into `master`

**Comment by fjaviersanchez** [comment]
In the meanwhile you can try to change this:

```
# Do the minimization.
       minimum = lmfit.minimize(residuals,parameters)
```
To this:

```
# Do the minimization.
        minimizer = lmfit.Minimizer(residuals,parameters,nan_policy='omit')
        minimum = minimizer.minimize()
```

**Comment by ismael-mendoza** [comment]
Thanks Javier !

**Comment by ismael-mendoza** [comment]
Pat and I thought it would be a good idea to toggle running lmfit, so I am opening a pull request that includes this toggle with a parameter `no-lmfit`
